service: my-social
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  deploymentBucket:
    name: my-social-deployment-bucket
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
package:
  patterns:
    - '!client/**'
