service: my-social-dev-app
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  deploymentBucket:
    name: my-social-deployment-bucket
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: GET
          cors:
            origins:
              - "http://localhost:3000"
            headers:
              - "Content-Type"
              - "X-Amz-Date"
              - "Authorization"
              - "X-Api-Key"
              - "X-Amz-Security-Token"
              - "Access-Control-Allow-Origin"
            allowCredentials: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - "http://localhost:3000"
            headers:
              - "Content-Type"
              - "X-Amz-Date"
              - "Authorization"
              - "X-Api-Key"
              - "X-Amz-Security-Token"
              - "Access-Control-Allow-Origin"
            allowCredentials: true
      - http:
          path: /posts
          method: GET
          cors:
            origins:
              - "http://localhost:3000"
            headers:
              - "Content-Type"
              - "X-Amz-Date"
              - "Authorization"
              - "X-Api-Key"
              - "X-Amz-Security-Token"
              - "Access-Control-Allow-Origin"
            allowCredentials: true
        
package:
  patterns:
    - '!client/**'
